name: Changelog

on:
  push:
    branch:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: srepollock/changelog-generator-action@master
      with:
        REPO_NAME: 'HugoPelletier/github-action-test'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PATH: 'CHANGELOG.md'
        COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'

